# Generated by Django 3.0.6 on 2020-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    @Warning : (3135, "'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ER
    ROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.")
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=20)),
                ('b_pub_date', models.DateField()),
                ('b_read', models.IntegerField(default=0)),
                ('b_comment', models.IntegerField(default=0)),
                ('is_Delete', models.BooleanField(default=False)),
            ],
        ),
    ]
